[package]
name = "kuwahara-filter"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
egui_extras = { version = "*", features = ["all_loaders"] }
image = { version = "0.25", features = ["jpeg", "png"] }
egui-file-dialog = "0.11.0"
rfd = "0.15.4"
